### PR TITLE
Caddyfile recipe

### PR DESCRIPTION
**Pull request by vanodevium**

### CODE REVIEW

**Comment by joanhey** [comment]
Thank you

**Comment by joanhey** [comment]
Of course @vanodevium

**Comment by joanhey** [comment]
And for your information, Caddy server is slower and scale worst than Nginx.

**Comment by vanodevium** [comment]
it depends :)

**Comment by joanhey** [comment]
image

**Comment by joanhey** [comment]
Latency
image

**Comment by vanodevium** [comment]
@joanhey 

Looks like a big problem... So sad.
Is there any tweaks to increase performance?

**Comment by joanhey** [comment]
Caddy server don't have any configurartion for performance.
It's really easy to use, but without any system-app configuration.

**Comment by vanodevium** [comment]
@joanhey 

You may laugh, but I just ran tests of caddy and nginx, and caddy performed better.

**Comment by joanhey** [comment]
> But for high performance, Nginx need to be correctly configured for any machine.

**Pull request merged**
